apiVersion: v2
name: n8n
version: 0.0.0
dependencies:
  - name: n8n
    version: 0.25.2
    repository: oci://8gears.container-registry.com/library
  - name: postgresql
    version: 14.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
