teslamate:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: power
            operator: In
            values:
            - high
  image:
    repository: teslamate/teslamate
    tag: 1.27.3
    pullPolicy: IfNotPresent
  env:
    # -- Set the container timezone
    TZ: America/Los_Angeles
    # -- Postgres database hostname
    DATABASE_HOST: '{{ include "common.names.fullname" .}}-postgresql'
    # -- Postgres database user name
    DATABASE_USER: teslamate
    # -- Postgres database password
    DATABASE_PASS: "{{ .Values.postgresql.auth.password }}"
    # -- Postgres database password
    DATABASE_NAME: "{{ .Values.postgresql.auth.database }}"
    # -- Disables the MQTT feature if `true`
    DISABLE_MQTT: "false"
    MQTT_HOST: mosquitto.mosquitto.svc.cluster.local
    ENCRYPTION_KEY: 7f4crTa8PDNuwIaulFWmDxPxlm4N5+vgyi3VTnn+v2rIb+bEjJiKQ7AnFe18UDh4
  service:
    main:
      ports:
        http:
          port: 4000
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.org/websocket-services: teslamate
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.2411.house"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hajimari.io/appName: Teslamate
        hajimari.io/icon: car-connected
      hosts:
        - host: &host teslamate.2411.house
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: teslamate-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true 
  postgresql:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: power
              operator: In
              values:
              - high
    enabled: true
    auth:
      postgresPassword: teslamate-pass
      username: teslamate
      password: teslamate-pass
      database: teslamate
    primary:
      persistence:
        enabled: true
        size: 32Gi
  dnsConfig:
    options:
      - name: ndots
        value: "1"

grafana:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: power
            operator: In
            values:
            - high
  image:
    repository: teslamate/grafana
    tag: "1.27"
    pullPolicy: IfNotPresent
  env:
    # -- Postgres database hostname
    DATABASE_HOST: 'teslamate-postgresql'
    # -- Postgres database user name
    DATABASE_USER: teslamate
    # -- Postgres database password
    DATABASE_PASS: "{{ .Values.postgresql.auth.password }}"
    # -- Postgres database password
    DATABASE_NAME: "{{ .Values.postgresql.auth.database }}"
    # -- Disables the MQTT feature if `true`
  service:
    main:
      ports:
        http:
          port: 3000
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.2411.house"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hajimari.io/appName: Teslamate-Grafana
        hajimari.io/icon: car-connected
      hosts:
        - host: &host teslagraph.2411.house
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: teslamate-grafana-tls-certificate
          hosts:
            - *host
  dnsConfig:
    options:
      - name: ndots
        value: "1"
