unifi:
  image:
    repository: jacobalberty/unifi
    tag: v7.3.76
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Unifi
        hajimari.io/icon: access-point
      hosts:
        - host: &host unifi-controller.2411.house
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: unifi-tls-certificate
          hosts:
            - *host
    portal:
      enabled: false

  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
      retain: true
  mongodb:
    enabled: true
    persistence:
      enabled: true
    image:
      tag: 4.4.15-debian-10-r8
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.31.225
