paperless:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Paperless
        hajimari.io/icon: file-document
      hosts:
        - host: &host paperless.2411.house
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: paperless-tls-certificate
          hosts:
            - *host
  env:
    PAPERLESS_DBHOST: postgresql
    PAPERLESS_REDIS: redis
  postgresql:
    enabled: true
  redis:
    enabled: true
