paperless:
  image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 1.8.0
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Paperless
        hajimari.io/icon: file-document
        nginx.ingress.kubernetes.io/proxy-body-size: 100m
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
        - host: &host paperless.2411.house
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: paperless-tls-certificate
          hosts:
            - *host
  env:
    PAPERLESS_DBHOST: paperless-postgresql
    PAPERLESS_REDIS: redis://paperless-redis-master
  postgresql:
    enabled: true
    persistence:
      enabled: true
      size: 4Gi
    image:
      repository: bitnami/postgresql
      tag: 11.17.0
  redis:
    enabled: true
    replica:
      replicaCount: 2
  persistence:
    data:
      enabled: true
      size: 4Gi
    media:
      enabled: true
      size: 4Gi
    consume:
      enabled: true
      size: 1Gi
