cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: "2024.10.0"
    imagePullPolicy: IfNotPresent

  replicaCount: 1

  metrics:
    enabled: false

  managed:
    enabled: true
    existingSecret: cf-tunnel-token

  local:
    enabled: false
