cloudflared:
  image:
    tag: 1213-4b75943d5943
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - hostname: '*.sananseline.olivergraff.com'
        service: tcp://ingress-nginx-controller.ingress-nginx:443
        originRequest:
          noTLSVerify: true
      - service: http_status:404

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
