cloudflared:
  image:
    tag: 1213-4b75943d5943
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - service: tcp://ingress-nginx-controller.ingress-nginx:443

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
