apiVersion: v2
name: longhorn
version: 0.0.0
dependencies:
  - name: longhorn
    version: 1.4.0
    repository: https://charts.longhorn.io
  - name: raw
    repository: https://charts.helm.sh/incubator
    version: 0.2.5

