longhorn:
  defaultSettings:
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  persistence:
    # If you have three or more nodes for storage, use 3; otherwise use 2
    defaultClassReplicaCount: 2  # TODO run DR test to see if we actually need 3
  preUpgradeChecker:
    jobEnabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    host: &host longhorn.2411.house
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "tunnel.2411.house"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
