app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/openspeedtest/latest
            tag: latest
  service:
    main:
      type: LoadBalancer
      annotations:
        tailscale.com/expose: "true"
      ports:
        http:
          port: 3000
          protocol: HTTP
