gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git
    hosts:
      - host: &host git.sananseline.olivergraff.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.sananseline.olivergraff.com
      database:
        DB_TYPE: postgres
        HOST: gitea-postgresql.gitea.svc.cluster.local.
        NAME: gitea
        PASSWD: gitea
        USER: gitea
      cache:
        ENABLED: true
        ADAPTER: memcache
        HOST: gitea-memcached.gitea.svc.cluster.local.

  persistence:
    storageClass: longhorn
  postgresql:
    persistence:
      storageClass: longhorn
