home-assistant:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.org/websocket-services: home-assistant
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home-assistant.sananseline.olivergraff.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: home-assistant-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true 
  dnsConfig:
    options:
      - name: ndots
        value: "2"
  image:
    tag: 2022.9.3
  lifecycle:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "sed -i 's~\\*\\*api_dict)~\\*\\*api_dict, ssl=False, proxy=\"http://192.168.32.2:9090\"})~' /usr/local/lib/python3.10/site-packages/yalexs/api_async.py"]
