home-assistant:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.org/websocket-services: home-assistant
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home-assistant.sananseline.olivergraff.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: home-assistant-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true 
  dnsConfig:
    options:
      - name: ndots
        value: "2"
  image:
    tag: 2022.9.3
  addons:
    codeserver:
      enabled: true
