app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/actualbudget/actual-server
            tag: 24.10.1-alpine
  service:
    main:
      ports:
        http:
          port: 5006
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host budget.2411.house
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: actualbudget-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 8Gi
      globalMounts:
        - path: /data
