ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      externalTrafficPolicy: Local
  tcp:
    22: gitea/gitea-ssh:22
